### PR TITLE
Use standard layout name web for pkg

### PR DESCRIPTION
**Pull request by MalloZup**
The scaffold of this project uses already `golang-standard` directory layout.
So use it for all dirs.

### Changes:

`webapp` -> `web`
# See

see https://github.com/golang-standards/project-layout#web

also is better to avoid duplicate pkg names we have 2 webapp

### CODE REVIEW

**Comment by stefanotorresi** [comment]
Could you please remove `node_modules` from checked in files? The diff is humongous.
I think you missed to update `.gitignore` to avoid that.

**Comment by MalloZup** [comment]
ok updating

**Comment by MalloZup** [comment]
@stefanotorresi ok updated. Should be ok now

**Comment by stefanotorresi** [comment]
> also is better to avoid duplicate pkg names we have 2 webapp

Well, one package path is `cmd/webapp` and one is just `webapp`, i.e. the final name is the same but the import path is different. Sadly this is a limitation of Go package system, and as far as I could see everybody usually resort to just alias child packages with snake_case notation in import statements.
It doesn't look quite right to me to keep `cmd/webapp` and the rest under `web`, so I would also change `cmd/webapp` to `cmd/web`. Opinions?

**Comment by MalloZup** [comment]
I'm ok to rename `cmd/web` or keep it as it is right now.

**Comment by MalloZup** [comment]
renamed accordingly

**Review by stefanotorresi — APPROVED** [review]

**Pull request merged**
